name: Publish extension to marketplace

on:
  push:
    branches:
      - master
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Connect GitHub workflows with repository
        uses: actions/checkout@v2
      - name: Publish extensions to Visual Studio Marketplace
        uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $AZURE_TOKEN"
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
